config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'events/new'
  post 'events/create'
  get 'events/show'
  get 'events/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :events, only: %i[create index show destroy]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
# frozen_string_literal: true

# models an event like a birthday party etc
class Event < ApplicationRecord
  # allows the calling of event.creator to find the user
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  # must include the through table
  has_many :attendances
  # this allows you to call Event.find(id).users
  has_many :attendees, through: :attendances, source: :user

  scope :past, -> { where('day < ?', Time.zone.today) }
  scope :future, -> { where('day > ?', Time.zone.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # prepopulates the creator_id when calling user.events.build()
  # foreign key is the id passed instead of the typical user_id
  has_many :events, foreign_key: 'creator_id'

  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user?
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to(login_path)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user?, only: %i[new create show index]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Event created!"
      redirect_to @event
    else
      flash.now[:danger] = "Unable to create event. Try again"
      render 'events/new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  private

  def event_params
    params.require(:event).permit(:day, :location, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_name(params[:name])
    if @user
      login(@user)
      redirect_to @user, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid name given"
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'You have successfully logged out'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = 'User successfully created'
      redirect_to @user
    else
      flash.now[:danger] = 'Unable to create user'
      render 'new'
    end
  end

  def show
    redirect_to(login_path) unless logged_in?

    @user = User.find(params[:id])
    @created_events = @user.events.where(creator_id: @user.id)
    @upcoming_events = current_user.events.future
    @previous_events = current_user.events.past
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the user via cookies
  # @param user [User] logs in the given user
  def login(user)
    session[:user_id] = user.id
  end

  # deletes the cookies
  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  # finds the user from cookies, if its nil, will return nil
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # checks if the user is logged in
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1> Create.html.erb </h1>

app/views/events/index.html.erb
<p><%= @events.count %></p>

<% @events.each do |event| %>
  <h3> Event Details: </h3>
  <p> day: <%= event.day %> </p>
  <p> location: <%= event.location %> </p>
  <p> description: <%= event.description %></p><br>
<% end %>

app/views/events/new.html.erb
<h2> Create a new event </h2>

<% if logged_in? %>
  <%= render 'shared/event_form' %>
<% end %>

app/views/events/show.html.erb
<h2> Day of the event: </h2>
<p id='day'><%= @event.day %></p>

<h2> Location of the event: </h2>
<p id='location'><%= @event.location %></p>

<h2> Description of the event: </h2>
<p id='description'><%= @event.description %></p>

<h2> Creator of the event: </h2>
<p id='creator'><%= @event.creator.name %></p>

<h2> Attendees: </h2>
<% @event.attendees do |attendee| %>
  <p> <%= attendee.name %> </p>
<% end %>

app/views/home/index.html.erb
<h1> Welcome to the home page! </h1>


<% if logged_in? %>
  <p><%= link_to "View your profile", current_user %></p>
  <p><%= link_to "Create an event", events_new_path %></p>
  <p><%= link_to "Logout", logout_path, method: :delete %></p>
<% else %>
  <p><%= link_to "Already a user? Login here", login_path %></p>
  <p><%= link_to "New user? Sign up here", signup_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">    
      <%= render 'shared/header' %>

      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>


      <%= yield %> 


      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event_form.html.erb
<%= form_with(model: @event) do |f| %>
  <%= render "shared/error_messages", object: f.object %> 

  <p><%= f.label :day %></p>
  <p><%= f.date_field :day %></p>

  <p><%= f.label :location %></p>
  <p><%= f.text_field :location %></p>

  <p><%= f.label :description %></p>
  <p><%= f.text_field :description %></p>

  <p><%= f.submit "Create event!" %></p>
<% end %>

app/views/shared/_header.html.erb
<ul class="navigation-links">
  <li><%= link_to "Home", root_url %></li>

  <% if logged_in? %>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Create event", events_new_path %></li>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Login", login_path %></li>
    <li><%= link_to "Signup", signup_path %></li>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<p>Create a new user</p>

<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: f.object %> 

  <%= f.label :name %>:<br>
  <%= f.text_field :name %><br><br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Username: </h1>
<p><%= @user.name %></p>
<p> Created at: <%= @user.created_at %> </p>
<p> Updated at: <%= @user.updated_at %></p>

<h2> Events Created: </h2>

<% @created_events.each do |event| %>
  <p>Event day: <%= event.day %></p>
  <p>Event location: <%= event.location %></p>
  <p>Event description: <%= event.description %></p>
<% end %>

<h2> Future Events: </h2>

<% @upcoming_events.each do |event| %>
  <p>Event day: <%= event.day %></p>
  <p>Event location: <%= event.location %></p>
  <p>Event description: <%= event.description %></p>
<% end %>

<h2> Past Events: </h2>

<% @previous_events.each do |event| %>
  <p>Event day: <%= event.day %></p>
  <p>Event location: <%= event.location %></p>
  <p>Event description: <%= event.description %></p>
<% end %>